### PR TITLE
fix: place footer to bottom when no full screen content present

### PR DESCRIPTION
**Pull request by ssxdev**
Date: 31-07-2024

Developer Name: Surendar Singh

---

## Issue Ticket Number

#148 

## Description

- Add CSS style for ".main" and ".content" div on the layout
- ".main" takes the full height of the screen
- ".content" takes up full empty screen space which automatically places the footer at the bottom

### Documentation Updated?

- [ ] Yes
- [x] No

### Under Feature Flag

- [ ] Yes
- [x] No

### Database Changes

- [ ] Yes
- [x] No

### Breaking Changes

- [ ] Yes
- [x] No

### Development Tested?

- [x] Yes
- [ ] No

## Screenshots
<details>
<summary>Screenshot 1</summary>

image
image
image
image

</details>

## Test Coverage
<details>
<summary>Screenshot 1</summary>
This fail tests are not related to the UI changes that I made.

image

</details>

### CODE REVIEW

**Review by tejaskh3 — COMMENTED** [review]
LGTM

**Comment by ssxdev** [comment]
> LGTM, but are these test cases failing for this branch only? which you have mentioned in the PR description

@tejaskh3 I forked the "develop" branch, which fails the same test cases

**Review by tejaskh3 — APPROVED** [review]

**Comment by vinit717** [comment]
image
Here some misalignment there can you please check this out

**Comment by ssxdev** [comment]
> Here some misalignment there can you please check this out

There is a gap because "Real Dev Squad Members" and "New User" are separate components that should have a list of members inside them. Both components are separated by some gap because both are separate categories. And also these changes are outside the scope of this particular task PR. TBH a complete revamp is required for this repo.

image

**Review by vinit717 — APPROVED** [review]

**Review by tejaskh3 — APPROVED** [review]

**Pull request merged**
